name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: support/create-release
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md

  release-windows:
    runs-on: windows-latest

    needs:
      - update-changelog

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Build Rust binary
        run: cargo build --release

      - name: Extract tag version (vX.Y.Z → X.Y.Z)
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: Prepare installer script with correct version
        run: sed -i 's/{{VERSION}}/$version/' installer.iss
        shell: bash

      - name: Confirm replaced version in installer.iss
        run: cat installer.iss
        shell: bash

      - name: Create installer
        run: iscc installer.iss

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${version}
          name: RS File Sorter v${version}
          body_path: CHANGELOG.md
          files: RSFileSorterSetup.exe
          token: ${{ github.token }}
